name: Scheduled Metafield Sync

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call Sync API
        run: |
          curl -X POST "${{ secrets.PRODUCTION_URL }}/api/metafields/sync" \
            -H "Authorization: Bearer ${{ secrets.SYNC_API_KEY }}" \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n" \
            -s --show-error
      
      - name: Log Sync Result
        if: always()
        run: echo "Sync job completed at $(date)"